name: Deploy Flutter Web

on:
  push:
    branches:
      - main # Remplace par 'master' si le nom de ta branche principale est master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Installation des dépendances
        run: flutter pub get

      - name: Build Web
        # Remplace NOM_DE_TON_REPO par le nom exact de ton dépôt GitHub (ex: /hus_app/)
        run: flutter build web --release --base-href "/hus_app/"

      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web